export enum EStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  PRODUCTION = 'PRODUCTION',
  FINISHED = 'FINISHED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  EXIST = 'EXIST',
  LOW_STOCK = 'LOW_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  NEW = 'NEW',
  PAUSED = 'PAUSED',
}
